### PR TITLE
#559 hamsini malli credits

### LINKED ISSUE #559: Hamsini Malli - Credits
### Description

Giving myself credit for the amazing developing work I will be doing at NER!

### Acceptance Criteria

See my name in my favorite color on the credits page.

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by hams7504**
## Changes

Added my name to the credits page

## Notes

Added my name to the credits page and wrote it in purple

image

Closes #559

### CODE REVIEW

**Review by Peyton-McKee — CHANGES_REQUESTED** [review]
Your code looks great! The only thing is it looks like you forgot to fill out your pull request. If you need help with figuring out what everything is, feel free to ask or look back in the tutorial document on confluence! Also make sure to assign yourself on the right hand side under “assignee”

**Comment by hams7504** [comment]
Done! It should be updated now.

**Review by Peyton-McKee — CHANGES_REQUESTED** [review]
One last thing, can you put a screenshot of the credits page in your PR? Visit localhost:3000/credits to see the page!

**Comment by hams7504** [comment]
Of course! It should be inserted now. Sorry about that!

**Review by Peyton-McKee — DISMISSED** [review]
LGTM!

**Review by RChandler234 — APPROVED** [review]
LGTM!

**Pull request merged**
