### PR TITLE
#1057: Added the Icons as requested to the Action dropdown

### LINKED ISSUE #1057: General - Change Request Detail Page Menu Icons
Add icons to the dropdown menu on the CR detail page of an unreviewed change request. These icons should go to the left of the text on the menu item. See how it's implemented for the Implement CR dropdown on a reviewed change request for an example of how to add icons to a menu item.

Icons:
Review - ContentPaste: https://mui.com/material-ui/material-icons/?query=clipboa&selected=ContentPaste
Delete - Delete Icon: https://mui.com/material-ui/material-icons/?query=trash&selected=Delete

### PR DESCRIPTION
**Pull request by ahnfikd7**
## Changes
Added the Icons as requested to the Action dropdown

_Explanation of changes goes here_
Review Icon and Delete Icon can be seen in an unreviewed Change Request Action Dropdown.

## Screenshots

pr1

pr2

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1057

### CODE REVIEW

**Comment by RChandler234** [comment]
@ahnfikd7 this has 143 files changed, it happened in your last commit somehow. You probably wanna close this PR, and make a new branch (making sure to create it off the newest version of develop) and just port your changes over to that, and then make a new PR

**Comment by ahnfikd7** [comment]
Thank you. I tried to pull the newest version of develop before creating this branch, however I received many merge conflicts, and had to resolve them manually. I'm not sure why it happened, if you could help me with it if I encounter that again that'll be really helpful!

**Comment by RChandler234** [comment]
> Thank you. I tried to pull the newest version of develop before creating this branch, however I received many merge conflicts, and had to resolve them manually. I'm not sure why it happened, if you could help me with it if I encounter that again that'll be really helpful!

You shouldn't get merge conflicts when pulling the latest version of develop unless you've committed changes on develop (which you should not be doing). If you can show me or a tech lead at the next meeting we can definitely help you out

**Comment by anthonybernardi** [comment]
tbh with how screwed up this branch is i'd recommend just making a new branch and doing all the changes again

check out the contributor guide if needed for git advice https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide

**Pull request closed without merging**
