### PR TITLE
#1496: remove any from loginpage

### LINKED ISSUE #1496: [Refactoring] - Remove `any` type from `src/frontend/src/pages/LoginPage/LoginPage.tsx`
### Description

Remove the use of the `any` type from LoginPage.tsx This may seem very simple, but the point of this is just to have you read through the codebase and understand the types/interfaces used in it, or make new ones that fit the shape of the data being used.

### Notes

Check #665 for notes on why we're doing this and pointers on what you should replace `any` with.

### Acceptance Criteria

`any` is not used as a type in LoginPage.tsx

### PR DESCRIPTION
**Pull request by wanke20**
## Changes

Changed type of res to 'GoogleLoginResponse | GoogleLoginResponseOffline'

## Checklist

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No yarn.lock changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1496

### CODE REVIEW

**Review by martin0he — CHANGES_REQUESTED** [review]
Looks great, all u need to do is add the checklist, u can copy it from someone else's PR

**Comment by wanke20** [comment]
> Looks great, all u need to do is add the checklist, u can copy it from someone else's PR

For some reason I can't copy and paste the boxes. Is what I did fine?

**Review by martin0he — APPROVED** [review]
looks great

**Review by RChandler234 — CHANGES_REQUESTED** [review]

**Comment by RChandler234** [comment]
See PR comment

**Pull request closed without merging**
