### PR TITLE
#702 removed any from work-packages-services

### LINKED ISSUE #702: [Refactoring] - Remove `any` type from work-packages.services
### Description

Remove the use of the `any` type from work-packages.services. This may seem very simple, but the point of this is just to have you read through the codebase and understand the types/interfaces used in it, or make new ones that fit the shape of the data being used.

### Notes

Check #665 for notes on why we're doing this and pointers on what you should replace `any` with.

### Acceptance Criteria

`any` is not used as a type in work-packages.services.

### Proposed Solution

`Ctrl + F`

### PR DESCRIPTION
**Pull request by harish-sundar**
Changed all types with "any" to actual data type in the work-packages-services file

Closes #702

### CODE REVIEW

**Review by Peyton-McKee — DISMISSED** [review]
LGTM

**Review by Ari-S-123 — DISMISSED** [review]

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
so this is not your fault because dependencies says it's a WBS_Element type but actually dependencies should be of type WbsNumber from shared

so what you'll need to do is fix the input argument of dependencies to be WbsNumber then everything you changed to be that as well

**Review by Peyton-McKee — APPROVED** [review]
LGTM

**Review by anthonybernardi — APPROVED** [review]
nice!

**Pull request merged**
