### PR TITLE
#142 StandardDetails & StageGateDetails

### LINKED ISSUE #394: Transition to MUI StageGateDetails.tsx (Col, Container, Row)
Transition StageGateDetails.tsx to material UI. Remove all react-bootstrap imports. Make visuals look as similar to before as possible. Fix any weird issues that switching to the different component causes.

### LINKED ISSUE #434: Transition to MUI StandardDetails.tsx (Container, Row, Col)
### Desired Changes

Transition StandardDetails.tsx to material UI. Remove all react-bootstrap imports. Make visuals look as similar to before as possible. Fix any weird issues that switching to the different component causes.

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by joshiarnav**
## Changes

- StageGateDetails.tsx
- StandardDetails.tsx

## Notes

Grid!!!!!!!! Typography!!!!!!!!

## Test Cases

- unchanged

## Screenshots

Screenshot 2022-11-16 at 8 33 25 PM

Screenshot 2022-11-16 at 8 33 47 PM

Screenshot 2022-11-16 at 8 34 09 PM

Screenshot 2022-11-16 at 8 34 34 PM

## To Do

- MUI

Closes #394 
Closes #434

### CODE REVIEW

**Review by anthonybernardi — APPROVED** [review]
awesome!

**Review by RChandler234 — CHANGES_REQUESTED** [review]
This is how your standard details looks 
image
Could you get it to look like it does on prod with the type and then the actual details to the right: 

image

**Comment by joshiarnav** [comment]
oops I thought that's what prod looked like, changing rn

**Comment by joshiarnav** [comment]
Screenshot 2022-11-20 at 2 45 19 PM

More like this?

**Comment by RChandler234** [comment]
image
looks like this with multiple Why's, can u change it so they're all aligned

**Review by RChandler234 — APPROVED** [review]
🔥

**Pull request merged**
