### PR TITLE
Update ReimbursementFormView.tsx

### PR DESCRIPTION
**Pull request by superhvarn**
## Changes

Everything in frontend involving expense type has "Code - Name" format.

## Screenshots
Screen Shot 2023-09-11 at 11 05 47 PM

Screen Shot 2023-09-11 at 11 00 59 PM
-ad49-d00920e980b7">
Screen Shot 2023-09-11 at 11 01 25 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes # (issue #1292 )

### CODE REVIEW

**Review by Peyton-McKee — APPROVED** [review]
Absolute W

**Review by RChandler234 — CHANGES_REQUESTED** [review]
image
I think you forgot to push whatever code adds the code to the expense type in the individual reimbursement request page, add that in and you should be good (MAKE SURE TO TAG YOUR COMMIT WITH THE TICKET #: #1292

**Review by Peyton-McKee — CHANGES_REQUESTED** [review]
If were gonna use this in a bunch of places we should make it a function called expenseTypePipe which essentially acts a toString method for this it can go in the utils.pies file

**Comment by superhvarn** [comment]
> If were gonna use this in a bunch of places we should make it a function called expenseTypePipe which essentially acts a toString method for this it can go in the utils.pies file

**Comment by RChandler234** [comment]
You need to tag your commits

**Pull request closed without merging**
