### PR TITLE
#580 Added my name to credits

### LINKED ISSUE #580: Roger Huang - Credits
### Description

Giving myself credit for the work I will do in NER!

### Acceptance Criteria

See my name in my fav color on the credits page

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file.

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by haoming5674**
## Changes

Added my name to the credits section of FinishLine homepage.

## Screenshots

image

image

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [x] item 1
- [x] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #580  (issue #)

### CODE REVIEW

**Review by Peyton-McKee — CHANGES_REQUESTED** [review]
Your code looks great! In your pull request however, make sure you fill out what you changed! And if you don’t use a section of your PR make sure you remove it entirely. Also, you do not need to screenshot your code, you only need to visit localhost:3000/credits to view what you actually changed and screenshot that screen! Also make sure you go through the checklist and check off everything you’ve done so you don’t forget anything!

**Comment by haoming5674** [comment]
Just added new screenshots and deleted some sections that weren't relevant, let me know if anything else needs fixing.

**Review by Peyton-McKee — APPROVED** [review]
Looks great! For future PRs, the second screenshot just needs to be a picture with your window being made as small as it can go so we can test the look of it when the dimensions have changed if that makes sense.

**Review by RChandler234 — APPROVED** [review]
Awesome!

**Pull request merged**
