### PR TITLE
#778 - Added sx to car filters checkbox to fix alignment

### LINKED ISSUE #778: [Frontend] - Gantt Car Filters Hover Effect Alignment
### Browser(s)

Chrome

### Platform(s)

Desktop

### Version(s)

production (main)

### Observed Behavior

The hover shadow thing is off-center for the car filters.

### Expected Behavior

They should be centered and aligned with the icons.

### Steps to Reproduce

1. Go to Gantt Page
2. Hover your cursor over one of the car filters

### Screenshots (as needed)

image

### PR DESCRIPTION
**Pull request by Boeufin**
## Changes

Added inline css using sx of the car handlers to fix the checkbox alignment

## Notes
None

## Test Cases

- Hover align when box1 checked
- Hover align when  box1 unchecked
- Hover align when box2 checked
- Hover align when  box2 unchecked

## Screenshots

Screenshot_20230301_164118

## To Do
- Disable rippleEffect on the second checkbox

Closes #778

### CODE REVIEW

**Review by Ari-S-123 — COMMENTED** [review]
This might need to account for the changes from https://github.com/Northeastern-Electric-Racing/FinishLine/pull/877.

**Comment by nezamj03** [comment]
we'll hold off on reviewing until #877 gets merged i suppose

**Comment by Ari-S-123** [comment]
You can merge in develop and check if your solution still works.

**Review by anthonybernardi — APPROVED** [review]
cool

**Pull request merged**
