### PR TITLE
Replaced all PM-Dashboard-v2 in the license statements of backend .ts files to FinishLine

### LINKED ISSUE #134: Repo - Update and Add license statements
### Description

We are open source and have license statements for files. However, they all say PM-Dashboard-v2 instead of FinishLine and stuff. Also I didn't add the license to a lot of new files when migrating to v3.

### Background

.

### Proposed Solution

find adn replace all, then add the statement to all new ts files in the backend that I missed

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by rombuski**
## Changes

Changed all .ts files license statement containing PM-Dashboard-v2 to FinishLine.

Closes #134  (issue #134 )

### CODE REVIEW

**Review by Ari-S-123 — CHANGES_REQUESTED** [review]
You have to change all the files in the codebase that have this at the top, not just .ts files. If there are .ts files in the backend which don't have the license statement at the top, add it to them.

**Comment by rombuski** [comment]
Went through the entire codebase this time  👍🏿

**Review by Ari-S-123 — CHANGES_REQUESTED** [review]
You missed a couple in `ProductManagement.md` and in the list below.

Screenshot 2022-10-13 123800

**Review by Ari-S-123 — CHANGES_REQUESTED** [review]
You missed `manifest.json` and `ProductManagement.md`

**Review by Ari-S-123 — APPROVED** [review]

**Review by anthonybernardi — DISMISSED** [review]
nice! next time tag your commits with your ticket number though

**Pull request merged**
