### PR TITLE
#1424 vendors alphabetical sort

### LINKED ISSUE #1424: Finance Fixes - Vendors Should be Sorted Alphabetically
Epic: #1274 

Currently, the vendors on the create/edit reimbursement request form are not sorted alphabetically. This ticket is to sort the list of vendors that are options in the dropdown in the frontend alphabetically.

The vendor field is "Purchased From:"
image
The dropdown:
image

### PR DESCRIPTION
**Pull request by thereare21**
## Changes

Added a sort method to the allVendors list, sorting by alphabetical order (ReimbursementFormView.tsx line 122)
Added multiple vendors to test alphabetical order(seed.ts line 688)

## Notes
Did not use localeCompare, instead created own comparison function for efficiency purposes.

## To Do
- none

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number - sorry, forgot to do this!! :/
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1424

### CODE REVIEW

**Review by ryanhowe28 — COMMENTED** [review]
Are you able to include screenshots of the vendors drop down sorted?

**Comment by thereare21** [comment]
Here is a screenshot of it running locally:

Screenshot 2023-09-25 at 12 25 31 AM

**Review by ryanhowe28 — CHANGES_REQUESTED** [review]
use localecompare

**Comment by thereare21** [comment]
added localeCompare

image

**Review by ryanhowe28 — APPROVED** [review]
Looks great!

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
