### PR TITLE
#1796 Added my name to credits

### LINKED ISSUE #1796: Alan Eng - Credits
### Description

credit for work to be done on finishline :)

### Acceptance Criteria

seeing my name on the credits page

### Proposed Solution

Add my name and color (blue) to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by alaneng-neu**
## Changes

added name to credits

## Screenshots

credits-full
credits-min

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1796

### CODE REVIEW

**Review by Aaryan1203 — CHANGES_REQUESTED** [review]
You should try to match the format of everyone else's so you can put it all on one line.

**Review by Aaryan1203 — DISMISSED** [review]
Great work!

**Review by RChandler234 — CHANGES_REQUESTED** [review]
You should include photos of what it looks like in the running app as well (see the confluence instructions)

**Review by alaneng-neu — COMMENTED** [review]
done

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
