### PR TITLE
#1887 Added my name to credits

### LINKED ISSUE #1887: Will Anderson - Credits
### Description

Giving myself credit for the amazing developing work I will be doing at NER!

### Acceptance Criteria

See my name in my favorite color on the credits page.

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by will-anderson0**
## Changes

Added my name into the credits page

## Screenshots
Screenshot 2024-01-22 at 2 07 40 PM

Screenshot 2024-01-22 at 2 13 15 PM

Checklist

It can be helpful to check the Checks and Files changed tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

 [ ] All commits are tagged with the ticket number
 [ ] No linting errors / newline at end of file warnings
 [ ] All code follows repository-configured prettier formatting
 [ ] No merge conflicts
 [ ] All checks passing
 [ ] Screenshots of UI changes (see Screenshots section)
 [ ] Remove any non-applicable sections of this template
 [ ] Assign the PR to yourself
 [ ] No yarn.lock changes (unless dependencies have changed)
 [ ] Request reviewers & ping on Slack
 [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1887

### CODE REVIEW

**Review by martin0he — APPROVED** [review]
lgtm

**Review by martin0he — CHANGES_REQUESTED** [review]
dont get rid of the PR template, never get rid of the checklist. and at the bottom where it says 'closes', it should say 'Closes #1887"

**Comment by will-anderson0** [comment]
Checklist
-added my name to array of names

closes #1887

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
