### PR TITLE
#2054: Added my name to the credits page

### LINKED ISSUE #2054: Gayathri Ramakrishnan - Credits
### Description

Giving myself credit for the developing work I will be doing at NER.

### Acceptance Criteria

See my name in purple on the credits page.

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by AngryGrapes**
## Changes

_Explanation of changes goes here_
Added my name and set color on the credits page

## Screenshots

_If you made UI changes you must post a screenshot of the whole page for each change in 1) a normal sized window and 2) the smallest possible window_
Screenshot 2024-02-06 at 10 28 40 PM
Screenshot 2024-02-06 at 10 29 03 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [✓] All commits are tagged with the ticket number
- [✓] No linting errors / newline at end of file warnings
- [✓] All code follows repository-configured prettier formatting
- [✓] No merge conflicts
- [✓] All checks passing
- [✓] Screenshots of UI changes (see Screenshots section)
- [✓] Remove any non-applicable sections of this template
- [✓] Assign the PR to yourself
- [✓] No `yarn.lock` changes (unless dependencies have changed)
- [✓] Request reviewers & ping on Slack
- [✓] PR is linked to the ticket (fill in the closes line below)

Closes #2054

### CODE REVIEW

**Review by Aaryan1203 — CHANGES_REQUESTED** [review]
Great work on the ticket! 

Make sure to fill out the template with a description of what you did and delete the parts of the template that you don't need. 

Also when adding a screenshot, can you add a screenshot of the website with your changes instead of the code?

**Review by AngryGrapes — COMMENTED** [review]
adding my name to the credits

**Review by Aaryan1203 — CHANGES_REQUESTED** [review]
for the PR, can you put a screenshot of the website with the updated changes instead of a screenshot of the code with the updated changes. Also delete the part of the template you didn't use where it says 'Explanation of changes goes here'

**Review by Aaryan1203 — APPROVED** [review]
Great work! LGTM!

**Pull request merged**
