### PR TITLE
#2947 Added my name to credits page

### LINKED ISSUE #2947: Eric Yao - Credits
### Description

Giving myself credit for the amazing developing work I will be doing at NER!

### Acceptance Criteria

See my name in my favourite colour on the credits page.

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by Yaomister**
## Changes

Added my name to the credits page.

## Screenshots

Screenshot 2024-11-14 at 2 25 18 PM

Closes #2947

### CODE REVIEW

**Review by alaneng-neu — CHANGES_REQUESTED** [review]
Looks good! Just make sure to resolve merge conflicts (can do it through GitHub) and I can approve it!

**Review by vsp05 — COMMENTED** [review]
Great work! If you need help dealing with merge conflicts, let me know and we can work through it together!

**Review by alaneng-neu — DISMISSED** [review]
LGTM

**Review by walker-sean — CHANGES_REQUESTED** [review]
Make sure to go through the checklist - could you please add some screenshots (there is a UI change) and remove unused sections of the template?

**Review by walker-sean — APPROVED** [review]

**Pull request merged**
