### PR TITLE
#1565 late wp reminder popup

### LINKED ISSUE #1565: [Frontend] - Add late WP reminder popup and mailbox
### Current Features

The leads of the work package don't get reminded to submit a change request for their work package that is overdue. They need to manually navigate to their work package details page and check if their work package end date has not passed yet. 

### Desired Additional Features

When the leads of the work package that is overdue log in to Finishline, they will see a modal/popup reminding them that their work package is overdue and providing the option to submit a change request. (By submitting the change request, the leads will have the option to submit a stage-gate or delay request for their work package).

There will be also an option to close the popup in case they can't submit CR right that second.

### PR DESCRIPTION
**Pull request by ItsEricSun**
## Changes

Added an overdue work package section to the homepage. When the leads of the work package go to their homepage and they have overdue work packages, they will see an alert reminding them that their work package is overdue and providing the option to submit a change request.

## Screenshots

What an alert looks like on dark mode:
image
image

What an alert looks like on light mode:
image
image

If the user clicks on the link or the create change request button, it brings them to the corresponding work package details page:
image

If the user has no overdue work packages or they click the 'x' on the alert to close it:
image

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1565

### CODE REVIEW

**Review by ryanhowe28 — CHANGES_REQUESTED** [review]
Both of these files are named the same. This can be confusing for someone looking for this in the code base. Differentiate the two

**Review by ryanhowe28 — CHANGES_REQUESTED** [review]
Can you see what it looks like when you have multiple over due work package? The way you made it, you might get an alert for each work package, not one alert with multiple buttons to take you to the respective change request. Might need to ask Zach Marino how he wants this done

**Comment by ItsEricSun** [comment]
What it looks like if user has 1 overdue work package.
image
What it looks like if user has 2 overdue work packages.
image
Same as before, clicking the link brings the user to the corresponding work package page so they can create a change request.
Create change request button was removed since it goes to the same place as the link.

**Review by RChandler234 — CHANGES_REQUESTED** [review]
I like this a lot and the code looks pretty good, I would say you should take more advantage of your space on the screen though. Try placing all the elements horizontally so that they all fit in one line, and wrap around like they are now, only if the screen is super small. Also, I would keep the create change request button, I think it does more to encourage the user to fix the problem (which IMO is the point of this feature)

**Comment by ItsEricSun** [comment]
Added in a grid so that each work package gets added horizontally across the alert and re-added the buttons.

image

image

**Review by RChandler234 — CHANGES_REQUESTED** [review]
you shouldn't be able to x out of the pop up

**Comment by ItsEricSun** [comment]
Removed the x button that closes the pop-up.

image

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
