### PR TITLE
#1909: added my name to credits

### LINKED ISSUE #1909: Samson Ajayi - Credits
### Description

Giving myself credit for the amazing developing work I will be doing at NER!

### Acceptance Criteria

See my name in my favorite color on the credits page.

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by sajayi12**
## Changes

Added Name to credits page

Screenshot 2024-01-23 at 9 57 48 PM

Screenshot 2024-01-23 at 9 29 32 PM

Closes #1909

### CODE REVIEW

**Review by Aaryan1203 — COMMENTED** [review]
Great work! Just remove the items on the pr template that you don't need and also add a zoomed in picture of your name

**Review by Aaryan1203 — CHANGES_REQUESTED** [review]
Just remove the items on the pr template that you don't need and also add a zoomed in picture of your name and you should be good

**Review by Aaryan1203 — APPROVED** [review]
Perfect!

**Review by RChandler234 — APPROVED** [review]
LTGM 🔥

**Pull request merged**
