### PR TITLE
#2948 Aaron Zhou – Credits

### LINKED ISSUE #2948: Aaron Zhou – Credits
### Description

I love NER

### Acceptance Criteria

See my name in my favorite color on the credits page.

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by aarowz**
## #2948 Aaron Zhou – Credits

Credit me!

Screenshot 2024-11-12 at 9 11 42 PM

Closes #2948

### CODE REVIEW

**Review by alaneng-neu — CHANGES_REQUESTED** [review]
Make sure you are using prettier to format your files! I think you should already have prettier downloaded from Launchpad, but make sure your "Format on save" setting in VS Code is checked on. If you don't have it downloaded, you can find it [here](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

**Comment by walker-sean** [comment]
Please make sure to give your PRs a relevant title; it can be hard to find them otherwise!

**Comment by walker-sean** [comment]
Closed as stale

**Review by vsp05 — APPROVED** [review]
LGTM!

**Review by alaneng-neu — APPROVED** [review]
LGTM

**Pull request merged**
