### PR TITLE
#388, #389, #390, #391, #396 - MUI Proposed Solutions

### LINKED ISSUE #388: Transition to MUI ProposedSolutionForm.tsx (Button, Col, Form, InputGroup, Row)
Transition ProposedSolutionForm.tsx  to material UI. Remove all react-bootstrap imports. Make visuals look as similar to before as possible. Fix any weird issues that switching to the different component causes.

### PR DESCRIPTION
**Pull request by Ari-S-123**
## Changes

Converted all Proposed Solution files to MUI

## Screenshots

Screenshot 2022-11-09 172824
Screenshot 2022-11-09 172928
Screenshot 2022-11-09 172946
Screenshot 2022-11-09 173738
Screenshot 2022-11-09 173803
Screenshot 2022-11-09 173840
Screenshot 2022-11-09 173900

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #388, #389, #390, #391, #396

### CODE REVIEW

**Review by RChandler234 — CHANGES_REQUESTED** [review]

**Comment by RChandler234** [comment]
image
the chips are showing up for me (I think they're getting cut off)
and the proposed solution form still has a visible scroll bar

**Comment by RChandler234** [comment]
image
image

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
code is cool and it works right, just reallllly think the chip should be in line with the other stuff on the review form

**Review by anthonybernardi — APPROVED** [review]
love it

**Pull request merged**
