### PR TITLE
#167: changed all stylesheet file names to kebab case

### LINKED ISSUE #167: Frontend - Rename stylesheets files
### Desired Changes

when we were renaming the frontend files, we accidentally made some files in pascal case that shouldn't be since they're not react components. Rename the files in the stylesheets folder to be lowercase (and hyphenated between words in the case of something like horizontal-list.module.ts).

make sure that all the imports of these files names are changed too (VSCode should hopefully do this for you)

make sure tests are still passing after you do this (yarn test:frontend) and that it runs right (`yarn:start`)

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by ethankong150**
## Changes

changed all stylesheet file names to kebab case

Closes #167

### CODE REVIEW

**Review by jamescd18 — COMMENTED** [review]
Folder names? Imports?

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
yeah to build off of james' review, folders should also be in the kebab case. also imports won't get changed by vscode but you can do a find all on vscode and search for like 'PascalCase.module' and replace all to be 'pascal-case.module'

**Review by Ari-S-123 — APPROVED** [review]
lgtm

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
running this locally it doesn't compile. seems like a few of the css and scss files still have capital letters but the imports have the correct lowercase. make sure after you change that everything looks like it's supposed to (you can compare with finishlinebyner.com) and if anythings unaligned or whatever then that means that something is broken

**Comment by ethankong150** [comment]
the app seems to be compiling fine for me without any changes... not exactly sure what's happening.

**Review by Ari-S-123 — APPROVED** [review]
lgtm

**Review by anthonybernardi — APPROVED** [review]
nice!

**Pull request merged**
