### PR TITLE
#1807: added my name to the credits page

### LINKED ISSUE #1807: Jake Langlois - Credits
### Description

Giving myself credit for the amazing developing work I will be doing at NER!

### Acceptance Criteria

See my name in my favorite color on the credits page.

### Proposed Solution

Add my name and favorite color to the "names

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by 23langloisj**
## Changes

_Explanation of changes goes here_
added my name to the credits page

Closes #1807

### CODE REVIEW

**Review by ryanhowe28 — CHANGES_REQUESTED** [review]
Can you include screen shots of what it looks like on the credits page. A full screenshot and a zoomed in one.

**Review by ryanhowe28 — DISMISSED** [review]
Great work thanks!

**Review by RChandler234 — CHANGES_REQUESTED** [review]
You also need to add Closes #1807 at the end of the PR description and then make sure your ticket has been correctly linked under development on the right. Also make sure to delete any sections of the PR template you're not using

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
