### PR TITLE
#1830-WaverlyHassman-credits

### LINKED ISSUE #1830: Waverly Hassman - Credits
### Description

Giving myself credit for the amazing developing work I will be doing at NER!

### Acceptance Criteria

See my name in my favorite color purple on the credits page.

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by wavehassman**
## Changes

added my name to the credits page in purple

## Screenshots
Screenshot 2024-01-18 at 7 26 03 PM
Screenshot 2024-01-18 at 7 26 30 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1830

### CODE REVIEW

**Review by martin0he — COMMENTED** [review]
Good job!
2 things:
- make sure you complete the entire checklist first before asking for a review (ie tick all the boxes)
- you seem to have a merge error. this means that your branch isnt up to date with the current working main branch. you could either, add the code github says is missing manually (which is just someone else's credit name) or just git pull to update your branch.
otherwise, looks good

**Comment by martin0he** [comment]
ok great your merge conflict is gone. the only thing remaining is that one of your tests failed. Prettier is what we use to format our code. go to whichever files u worked on, right click, format document with prettier. and push your commit again.

**Comment by wavehassman** [comment]
I reformatted it, but when I try to push my commit again it says its already up to date

**Comment by martin0he** [comment]
image

On this page, modify your code very slightly like changing the color of your text, and then format your document again with prettier and you should be able to push again. in vscode, you should see a "1" whenever you make a new change on your branch on the left side toolbar of your screen on the Github icon.

**Review by martin0he — DISMISSED** [review]
good job

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
