### PR TITLE
#265: Added 2 tests for createWorkPackage

### LINKED ISSUE #265: Backend - Test createWorkPackage Endpoint (part 3)
### Description

Write some unit tests for the createWorkPackage endpoint. To work on this ticket, you will need to read through the endpoint to learn how it works.

### Acceptance Criteria

The following cases should be covered:
* the associated wbsElem returns null
* the associated wbsElem does not have a project object

### Proposed Solution

Check out this epic https://github.com/Northeastern-Electric-Racing/FinishLine/issues/238 for resources and tips on how to write these tests.

### PR DESCRIPTION
**Pull request by akale22**
## Changes
Created tests for the createWorkPackage endpoint for when the associated wbsElem returns null and when the associated wbsElem does not have a project object.

## Notes
When doing this, I was a little confused by some of the project structure and what it meant specifically for a wbsElem to not have a project object, so I tried my best to write tests mimicking the previously written tests. I wasn't sure if this was actually testing the right thing though and wanted some feedback. 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #265

### CODE REVIEW

**Comment by z-roth** [comment]
Looks good to me so far! @anthonybernardi knows a bit more about testing so he can provide more feedback on this if there needs to be any changes. Solid work!

**Review by z-roth — COMMENTED** [review]
Looks good to me so far! @anthonybernardi knows a bit more about testing so he can provide more feedback on this if there needs to be any changes. Let's look into fixing tests next. Solid work!

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
nice! only change is prettier formatting is needed

**Review by anthonybernardi — APPROVED** [review]
nice!

**Pull request merged**
