### PR TITLE
#637-Changed Alert to Toast

### LINKED ISSUE #637: [Frontend] - Replace alert() with useToast() in CreateWorkPackageForm
### Description

Replace the alert() call(s) with useToast() in CreateWorkPackageForm.

### Acceptance Criteria

The alert() call(s) should be replaced by useToast() in CreateWorkPackageForm.

### Proposed Solution

`Ctrl + Shift + F`

Please refer to the notes in the [epic](https://github.com/Northeastern-Electric-Racing/FinishLine/issues/633) for more guidance.

### PR DESCRIPTION
**Pull request by ahnfikd7**
## Changes
Changed alert() to useToast()
_Explanation of changes goes here_
Used the useToast() hook to define toast, and then used toast.error, which does the same thing as alert.
Also, modified it to include the autoHideDuration property.

Lastly, added the jest.mock for the toast in CreateWorkPackageform.test
## Notes
I cannot login to localhost:3000/login for some reason . It just says Students must use their Husky Google account, but I'm already using it.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #637

### CODE REVIEW

**Review by Ari-S-123 — CHANGES_REQUESTED** [review]
You can look at `ReviewChangeRequestView.test` for an example of how to mock the toasts hook file for the tests.

**Comment by ahnfikd7** [comment]
I added the autoHideDuration property of useToast, but I'm not sure where the issue is because the test is still not passing. Also, I found a file ReviewChangeRequestView.tsx, not ReviewChangeRequestView.test

**Comment by Ari-S-123** [comment]
> I added the autoHideDuration property of useToast, but I'm not sure where the issue is because the test is still not passing. Also, I found a file ReviewChangeRequestView.tsx, not ReviewChangeRequestView.test

It's in the tests folder.

**Review by anthonybernardi — APPROVED** [review]
awesome!

**Pull request merged**
