### PR TITLE
Update CreditsPage.tsx

### LINKED ISSUE #1808: Yulan Wang - Credits
### Description

Giving myself credit for the amazing developing work I will be doing at NER!

### Acceptance Criteria

See my name in my favorite color on the credits page.

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file.

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by yulanwang**
## Changes

Update credits page 

## Notes

Added my name to the credits page

## Screenshots

Screenshot 2024-01-20 at 7 45 17 PM

Screenshot 2024-01-20 at 7 45 21 PM

Closes #1808

### CODE REVIEW

**Review by RChandler234 — CHANGES_REQUESTED** [review]
Can you assign the PR to yourself, fix the prettier (I think removing the extra line on line 186 will work), and put pictures of your name on the actually website running locally (not of the code)

**Comment by yulanwang** [comment]
added changes and correct screenshot.

**Comment by yulanwang** [comment]
Everything should be fixed now.

**Review by RChandler234 — APPROVED** [review]
Nice Job!

**Pull request merged**
