### PR TITLE
#2684: Changed the Start Date Request for a Work Package Form from YY…

### LINKED ISSUE #2684: Work Package Form - Start Date Requests YYYY-MM-DD but takes MM-DD-YYYY
### Browser(s)

_No response_

### Platform(s)

_No response_

### Version(s)

_No response_

### Observed Behavior

The specified input does not match with the actual input

### Expected Behavior

Specify that the user should input MM-DD-YYYY

### Steps to Reproduce

Go to the create or edit WP form

### Screenshots (as needed)

_No response_

### PR DESCRIPTION
**Pull request by justalittlemushroom**
…YY-MM-DD to MM-DD-YYYY

## Changes

Changed the Start Date Request for a Work Package Form from YYYY-MM-DD to MM-DD-YYYY

## Screenshots
Screenshot 2024-11-20 at 19 58 26
Screenshot 2024-11-20 at 19 58 29

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2684

### CODE REVIEW

**Review by Peyton-McKee — APPROVED** [review]

**Review by Peyton-McKee — CHANGES_REQUESTED** [review]
Can you change the end date one as well sorry

**Review by vsp05 — DISMISSED** [review]

**Comment by vsp05** [comment]
dont push your yarn.lock changes!

**Comment by vsp05** [comment]
make sure to not push your yarn.lock changes! otherwise, looks good

**Review by vsp05 — APPROVED** [review]
LGTM! Great Work!

**Review by Peyton-McKee — APPROVED** [review]

**Pull request merged**
