### PR TITLE
#1397 Added my name to Credits

### LINKED ISSUE #1397: Raymond Tsai - Credits
### Description

Giving myself credit lol >:)

### Acceptance Criteria

see my name on the credits page

### Proposed Solution

add it to the 'CreditsPage.tsx' file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by thereare21**
## Changes

Added my name to the CreditsPage.tsx file

## Notes

Struggled to publish my branch because I wasn't invited initially.

## Screenshots
image

image

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1397

### CODE REVIEW

**Comment by tigerhippo** [comment]
This looks good! Nice job :)

Not sure what's happening but the normal tests and checks aren't appearing on your PR. You can type 'yarn test:frontend' and 'yarn test:backend' on your branch (in the command line) to make sure you pass all test cases. I already did this for you and you are passing all the tests, but this is just for future reference.

Also something weird but it looks like a lot of things were changed in the CreditsPage.tsx file code in this PR, and when I went onto your branch and looked at the credits page from there, it seemed like a lot of changes were made (many names were added). Can you go back and check in the code (and also on the credits page) that only your name was added?

**Comment by RChandler234** [comment]
> This looks good! Nice job :)
> 
> Not sure what's happening but the normal tests and checks aren't appearing on your PR. You can type 'yarn test:frontend' and 'yarn test:backend' on your branch (in the command line) to make sure you pass all test cases. I already did this for you and you are passing all the tests, but this is just for future reference.
> 
> Also something weird but it looks like a lot of things were changed in the CreditsPage.tsx file code in this PR, and when I went onto your branch and looked at the credits page from there, it seemed like a lot of changes were made (many names were added). Can you go back and check in the code (and also on the credits page) that only your name was added?

Checks don't show up when you have merge conflicts, I can j take care of them

**Review by RChandler234 — CHANGES_REQUESTED** [review]
Make sure to add the ticket number at the bottom here next to the first hashtag (this makes sure that the original ticket is closed when the PR is): 
image

Also make sure to delete all the unused parts of the template (like the test cases section). You can edit the PR description by clicking the ... in the top right

**Comment by tigerhippo** [comment]
Nice work Raymond! This looks good to me!

**Review by RChandler234 — APPROVED** [review]

**Pull request merged**
