### PR TITLE
#670: replace all any type (draft)

### LINKED ISSUE #670: [Refactoring] - Remove `any` type from ReactHookEditableList
### Description

Remove the use of the `any` type from ReactHookEditableList. This may seem very simple, but the point of this is just to have you read through the codebase and understand the types/interfaces used in it, or make new ones that fit the shape of the data being used.

### Notes

Check #665 for notes on why we're doing this and pointers on what you should replace `any` with.

### Acceptance Criteria

`any` is not used as a type in ReactHookEditableList.

### Proposed Solution

Use `Ctrl + F` to find all instances of any, and replace it with the correct type

### PR DESCRIPTION
**Pull request by madgengle**
## Changes
Changed the two any types to more specific types.
The first worked, the second any type (append) created issues in other files and wouldn't work despite the work of Megan and  Ari.
## Notes
register still has an any type within the UseFormRegister and could still possibly be narrowed down. append would likely use UseFieldArrayAppend but was creating issues with other files, so it is still an any type. This is currently a draft and in need of help from other people (Anthony).

## To Do
- Narrow down the type going into UseFormRegister
- Fix the issues with UseFieldArrayAppend so that it can be used as the type for append

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #670

### CODE REVIEW

**Review by Peyton-McKee — COMMENTED** [review]
So theres two courses of action here... You can create an | for every possible way we use this function, so like fill out the type for the edit project register i.e. 
    name: string;
    budget: number;
    slideDeckLink: string | undefined;
    bomLink: string | undefined;
    taskListLink: string | undefined;
    googleDriveFolderLink: string | undefined
summary: string;
    ... 6 more ...;
    constraints: {
        ...;
    }[]; | any other way that we use it,(look at references)

OR 

We accept that this is a generic type and in this situation any is an acceptable use case

**Review by tigerhippo — COMMENTED** [review]
You can get rid of unused import statements, namely UseFieldArrayRemove, FieldArray, and FieldArrayMethodProps.

**Comment by madgengle** [comment]
Hey @tigerhippo, I have switched the two any types to be the more specified fields (UseFormRegister and UseFieldArrayAppend). I also got rid of anything imported that was not used within the file. Can you look over the new commit?

**Comment by tigerhippo** [comment]
LGTM!

**Review by anthonybernardi — CHANGES_REQUESTED** [review]
so if you run the app you will see that it crashes. not sure what the best fix for this is cuz it's kinda a weird type

**Review by tigerhippo — COMMENTED** [review]
The code looks good but I'm still getting an error when running FinishLine on your branch

**Review by tigerhippo — COMMENTED** [review]
LGTM!

**Review by RChandler234 — APPROVED** [review]
LGTM!

**Pull request merged**
