### PR TITLE
#718 change create change request buttons

### LINKED ISSUE #718: [Frontend] - Change CreateChangeRequest to use NER Buttons
### Description

In the pursuit of making the looking and feel of our app consistent, we wanna use new components that have been made (NERSuccessButton/NERFailButton) in every place where we currently have a cancel/save button combo. By doing this, we not only make all these save/cancel buttons adhere to the new look, but we also allow ourselves to change how all these save buttons look in the future by changing only one file!

For this ticket, change the save/cancel buttons in the CreateChangeRequest component to use the NERSuccessButton/NERFailButton component rather than just the plain MUI button.

Put the cancel on the left, and the submit on the right

### Acceptance Criteria

The save/cancel buttons on CreateChangeRequest use NERSuccessButton/NERFailButton and not Button
The save/cancel buttons on that page looks like the new success/cancel buttons (green and red contained, see the edit members section on a teams specific page to see a good example of how it looks).
Verify nothing looks weird/ everything works as it did before.
Buttons should be 2 px apart, good example: https://github.com/Northeastern-Electric-Racing/FinishLine/pull/731

### Proposed Solution

All the props should be the same, all you need to do is swap out the old for the new / for the Save/Cancel buttons respectively.

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by hhmai**
## Changes

Changed buttons to use NERFail and NERSuccess buttons

## Notes

_Any other notes go here_

## Test Cases

- Use of submit button adds change request to list of requests
- Use of cancel button brings back to Create Change Request page

## Screenshots

image

image

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #718

### CODE REVIEW

**Review by Peyton-McKee — APPROVED** [review]
LGTM Great work!

**Review by Peyton-McKee — CHANGES_REQUESTED** [review]
We decided that we actually want these buttons in the bottom right of whatever container theyre in, can you make that change real quick. heres an example. We also want the space between the buttons to only be 2px. Right now its set to 4 because both the success button and fail button have their mx style set to 2.

Screen Shot 2023-01-27 at 12 12 34 PM

**Review by Peyton-McKee — APPROVED** [review]
LGTM!

**Review by anthonybernardi — APPROVED** [review]
nice!

**Pull request merged**
