### PR TITLE
#1339 - Added my name to credits

### LINKED ISSUE #1339: Srihari Raman - Credits
### Description

Giving myself credit for genius work that will be produced by me!

### Acceptance Criteria

My name appearing on the credits page

### Proposed Solution

Add my name and favorite color to the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by thealphacubicle**
## Changes

I've added my name to the credits page

## Notes
N/A

Closes #1339

### CODE REVIEW

**Review by Peyton-McKee — APPROVED** [review]
Well Done!

**Review by Peyton-McKee — DISMISSED** [review]
oops actually can u add a screen shot of the change you made to this PR since u made a UI change

**Comment by thealphacubicle** [comment]
Got it, here is the UI change:

Screenshot 2023-09-11 at 11 17 04 PM

<div></div>

Screenshot 2023-09-11 at 11 17 51 PM

**Review by RChandler234 — APPROVED** [review]
Good shit, you should only request your tech lead or me for reviews in the future tho fyi

**Pull request merged**
