### PR TITLE
#403/#720 Updated stage gate buttons and fixed crashing

### LINKED ISSUE #403: General - Get Rid of Dev Warnings
### Description

When I run the app locally on node 16, i get some errors about certain values in our fields being deprecated. Get rid of these warnings because I think they're annoying, but make sure that taking out these fields doesn't mess with things like deployment or anything (since the `main` field gets used to say what the index is so idk how we remove it tbh)

### Acceptance Criteria

,

### Proposed Solution

,

### Mocks

Screen Shot 2022-10-27 at 8 09 29 PM

### LINKED ISSUE #720: [Frontend] - Change StageGateWorkPackageModal to use NER Buttons
### Description

In the pursuit of making the looking and feel of our app consistent, we wanna use new components that have been made (NERSuccessButton/NERFailButton) in every place where we currently have a cancel/save button combo. By doing this, we not only make all these save/cancel buttons adhere to the new look, but we also allow ourselves to change how all these save buttons look in the future by changing only one file!

For this ticket, change the save/cancel buttons in the StageGateWorkPackageModal component to use the NERSuccessButton/NERFailButton component rather than just the plain MUI button.

Put the cancel on the left, and the submit on the right

### Acceptance Criteria

The save/cancel buttons on StageGateWorkPackageModal use NERSuccessButton/NERFailButton and not Button
The save/cancel buttons on that page looks like the new success/cancel buttons (green and red contained, see the edit members section on a teams specific page to see a good example of how it looks).
Verify nothing looks weird/ everything works as it did before.

### Proposed Solution

All the props should be the same, all you need to do is swap out the old for the new / for the Save/Cancel buttons respectively.

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by zmar234**
## Changes

FOR #720:

In StageGateWorkPackageModal.tsx, I first imported the new NER success and fail components on lines 23 and 24. Then, I replaced the buttons that were there with the NER buttons on lines 117-122 and gave them the appropriate properties to function.

FOR #403:

In DescriptionPageBlock.tsx I changed line 10 to include "isUnderWordCount, countWords" in the import statement. I am unsure if this fixed the problem as the problem did not go away until the second change but I digress. In package.json, I changed "dist/index.js" to "index.ts" which solved the problem.

## Notes

This PR is most likely marked under #403 but it also includes #720 I apologize for the confusion next time I will make separate PRs! USE THE LATEST COMMIT AND DISREGARD COMMIT NAMES

## Screenshots

image
image

Closes #403
Closes #720

### CODE REVIEW

**Review by nezamj03 — DISMISSED** [review]
nice!

**Comment by RChandler234** [comment]
Code looks fine, will test when I get home, might have you tweak the position of the buttons a bit

**Review by RChandler234 — CHANGES_REQUESTED** [review]

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Review by anthonybernardi — APPROVED** [review]
cool!!

**Pull request merged**
