### PR TITLE
#2946 Added: my name to credits

### LINKED ISSUE #2946: Jason Kuo - Credits
### Description

Giving myself credit for the work I'm about to do on NER Finishline!

### Acceptance Criteria

Seeing my name on the credits page

### Proposed Solution

Add my name and favorite color to the "names" array on the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by jasonk55**
## Changes

Added my name to the names array in the CreditsPage.tsx file

## Screenshots

Screenshot 2024-11-12 at 8 48 23 PM

Screenshot 2024-11-12 at 8 49 57 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #2946

### CODE REVIEW

**Review by alaneng-neu — CHANGES_REQUESTED** [review]
You will need to resolve conflicts before merging. Also make sure in your PR description you are filling in the closes line, i.e. "Closes #2946"

**Comment by jasonk55** [comment]
> You will need to resolve conflicts before merging. Also make sure in your PR description you are filling in the closes line, i.e. "Closes #2946"

Should be good now

**Review by alaneng-neu — APPROVED** [review]

**Review by vsp05 — APPROVED** [review]
great work!

**Review by walker-sean — APPROVED** [review]
fire emoji

**Pull request merged**
