### PR TITLE
#1818: added my name to credits page

### LINKED ISSUE #1815: Jaden Zhou - Credits
### Description

Giving myself credit for the amazing developing work I will be doing at NER!

### Acceptance Criteria

See my name in my favorite color on the credits page.

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by JadenZhub**
## Changes

added line for my name and color of text

## Notes

_Any other notes go here_

## Screenshots

Screenshot 2024-01-17 at 10 15 45 PM
Screenshot 2024-01-17 at 10 16 19 PM

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1815

### CODE REVIEW

**Review by Aaryan1203 — DISMISSED** [review]
Great work!

**Review by RChandler234 — CHANGES_REQUESTED** [review]
Make sure to link the PR to the ticket correctly, you need to put Closes #1818 without the space in the description and make sure it's linked under development on the right

**Comment by JadenZhub** [comment]
I think I messed up my #s, but I removed the space, and linked it to the original issue.

**Review by RChandler234 — DISMISSED** [review]
LGTM 🔥

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
