### PR TITLE
#1372: Added my name to credits

### LINKED ISSUE #1372: Sathvik Charugundla - Credits
### Description

Can't wait for coding with NER!

### Acceptance Criteria

My name will be with my favorite color on the credits page

### Proposed Solution

Add "Sathvik Charugundla" and "Red" to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by patriots1**
## Notes

It was okay. As I had no experience with Git, it was naturally challenging. I do feel that I have a basic grasp of how to use Git because of this activity. 

## Screenshots

image

image

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #1372

### CODE REVIEW

**Comment by tigerhippo** [comment]
This looks great! Nice job :) 

For future reference just make sure you attach a screenshot of what the actual credits page looks like on your local branch (with your change). We don't actually need a screenshot of your code because we can look at that already.

Not sure what's happening but the normal tests and checks aren't appearing on your PR. You can type 'yarn test:frontend' and 'yarn test:backend' on your branch (in the command line) to make sure you pass all test cases. I already did this for you and you are passing all the tests, but this is just for future reference.

**Review by RChandler234 — CHANGES_REQUESTED** [review]
Hi Sathvik! Can you delete the changes section in the template since you're not using it and add a screenshot of the whole credits page with your name on it, not just a screenshot of your name specifically. For frontend features we wanna see how the page looks as a whole with your additions, not just what you added in isolation. Once those changes are done we can get this one merged!

Also, please only request me or your tech lead as a reviewer in the future

**Comment by patriots1** [comment]
Hi Reid! Thanks for the input. I've updated the template to reflect the changes you requested. Also, who will be my tech lead?

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
