### PR TITLE
#1377: Added my name to credits

### LINKED ISSUE #1377: Liu von Engelbrechten - Credits
### Description

Add my name to the credits page

### Acceptance Criteria

See my name in my favorite color on the credits page

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by lvonengel**
## Changes

I added my name to the credits page

## Screenshots

Credits Page With Liu

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [x] All commits are tagged with the ticket number
- [x] No linting errors / newline at end of file warnings
- [x] All code follows repository-configured prettier formatting
- [x] No merge conflicts
- [x] All checks passing
- [x] Screenshots of UI changes (see Screenshots section)
- [x] Remove any non-applicable sections of this template
- [x] Assign the PR to yourself
- [x] No `yarn.lock` changes (unless dependencies have changed)
- [x] Request reviewers & ping on Slack
- [x] PR is linked to the ticket (fill in the closes line below)

Closes #1377  (issue #)

### CODE REVIEW

**Comment by tigerhippo** [comment]
Looks great to me, nice job!

**Review by RChandler234 — CHANGES_REQUESTED** [review]
Hi Liu! You need to add a screenshot of your name added to the credits page (you can do this by starting the app locally and going to localhost:3000/credits. You should also delete the unused parts of the pull request template. Once you make those changes, we can get this merged!

**Comment by lvonengel** [comment]
> Hi Liu! You need to add a screenshot of your name added to the credits page (you can do this by starting the app locally and going to localhost:3000/credits. You should also delete the unused parts of the pull request template. Once you make those changes, we can get this merged!

**Comment by lvonengel** [comment]
> Hi Liu! You need to add a screenshot of your name added to the credits page (you can do this by starting the app locally and going to localhost:3000/credits. You should also delete the unused parts of the pull request template. Once you make those changes, we can get this merged!

**Comment by tigerhippo** [comment]
Great job Liu, looks good to me

**Review by RChandler234 — APPROVED** [review]
LGTM 🔥

**Pull request merged**
