### PR TITLE
#555: added my name to credits

### LINKED ISSUE #555: Neil Satsangi - Credits
### Description

Giving myself credit for my work at NER

### Acceptance Criteria

See my name in my favorite color on the credits page

### Proposed Solution

Add my name and favorite color to the "names" array in the CreditsPage.tsx file

### Mocks

_No response_

### PR DESCRIPTION
**Pull request by NeilSatsangi**
## Changes

I added my name to the credits section

## Test Cases

- Case A
- Edge case
- ...

## Screenshots

Screen Shot 2023-01-18 at 9 09 12 PM

_If you did any manual testing (e.g., with Postman), put screenshots of the http request and before and after of the db_

_If none of this applies, you can delete this section_

## To Do

_Any remaining things that need to get done_

- [ ] item 1
- [ ] ...

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured prettier formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] No `yarn.lock` changes (unless dependencies have changed)
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #555

### CODE REVIEW

**Review by Peyton-McKee — CHANGES_REQUESTED** [review]
One tiny change! Your prettier check is failing, I believe it is because you need to add a space before your closing brace. If your VSCode is set to run prettier on save, you can also command+s your file and it should fix it that way too!

**Review by NeilSatsangi — COMMENTED** [review]
I added the space, I think it should be good now

**Review by Peyton-McKee — DISMISSED** [review]
LGTM! For future PRs make sure to remove any parts that you don’t end up using, like todo/test cases!

**Review by RChandler234 — APPROVED** [review]
nice!

**Pull request merged**
